#!/usr/bin/env bash

# Fix GNOME/Wayland issue where it always tries to screenshot the leftmost monitor instead of what is selected
export QT_QPA_PLATFORM=xcb
# wl-copy temp due to https://github.com/flameshot-org/flameshot/issues/4116
zsh -c 'flameshot gui -r | wl-copy'
